# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
client: dws
appGroup: dev
debug: "*"
nodenv: dev
replicaCount: 1
image:
  repository: us.icr.io/dwsmicroapp-dev/taskform-angular
  tag: latest
  pullPolicy: Always
  imagePullSecret: all-icr-io
service:
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "200m"
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

